module.exports = function (grunt) {
    grunt.initConfig({
        watch:{
            jade:{
                files:["views/**"],
                option:{
                    livereload:true
                }
            },
            js:{
                files:["public/js/**","models/**.js","schema/**/*.js"],
                task:["jshint"],
                option:{
                    livereload:true
                }
            }
        },
        nodemon:{
            dev:{
                option:{
                    file:"app.js",
                    args:[],
                    ignoredFiles:["README.md","node_module/**",".DS_Store"],
                    watchedExtensions:["js"],
                    watchedFolders:["./"],
                    debug:true,
                    delayTime:1,
                    env:{
                        PORT:3000
                    },
                    cwd:__dirname
                }
            }
        },
        concurrent:{
            tasks:["nodemon","watch"],
            options:{
                logConcurrentOutput:true
            }
        }
    })

    grunt.loadNpmTasks("grunt-contrib-watch")
    grunt.loadNpmTasks("grunt-nodemon")
    grunt.loadNpmTasks("grunt-concurrent")

    //设置不要因为写语法错误而中断整个服务
    grunt.option("force",true)
    grunt.registerTask("default",["concurrent"])
}
